### PR TITLE
Make hydrate asynchronous

### PR DESCRIPTION
**Pull request by timseverien**
This change makes `conditioner.hydrate()` asynchronous, allowing the developer to run code after all bound modules are initialized and mounted. E.g.:

```js
const boundModules = await conditioner.hydrate(document.documentElement);

// Do something with boundModules
```

same code using the `Promise` API:

```js
conditioner.hydrate(document.documentElement).then((boundModules) => {
  // Do something with boundModules
});
```

### CODE REVIEW

**Comment by rikschennink** [comment]
Nice. 

But now we have to wait for all modules to load before we can "use" any of them? What if some are conditionally loaded? I think it would be better to create a helper function that can optionally be wrapped around the hydrated modules array and will resolve when all modules are loaded (that's how it worked in Conditioner V1 btw).

**Comment by acstll** [comment]
I don't have an opinion (yet) about this. I now only would like to point out that it is a breaking change.

**Comment by timseverien** [comment]
Let me clarify my use-case. My application implements a mediator pattern where a parent module mediates the communication between two other modules. The communication is done via the publish-subscribe pattern, so the parent module needs a reference to the child modules. Storing the reference in memory is easily done with a callback passed to `addPlugin()`.

Detecting whether a module‘s dependencies are imported/constructed/mounted isn’t easy. Before the PR, I did came up with the idea to use `moduleDidMount()` to count how many modules are mounted. If the count equals the number of modules found. Aside from some trivial downsides, gracefully handing errors outside of Conditioner is complex.

The proposed `Promise`-based solution isn’t perfect, but helps enormously dealing with errors. I’m more than willing to pivot to a better solution or find a good solution that works without changing Conditioner.

@rikschennink the current implementation in this PR just waits for all modules _without_ context. This might be confusing for users, so that is something we should definitely improve in the docs if we choose to accept this PR. This PR does help enormously run some code after non-conditional modules are mounted.

@acstll yeah it definitely is a breaking change.

**Comment by acstll** [comment]
Thank you for the clarification and sharing your use-case.

To me it sounds like you do need something more than `conditioner`. Something being a framework, or some stage management tool.

I think that when you need two or more modules to communicate between them you're sacrificing one of the key advantages of this library, which is the fact you can add `data-module="foo"` to an element or many elements, wherever in the document and it should just work. (I think there's a nerdy word for that, like resilience or idempotency, I don't know.) 

In about a year of using it, I have encountered two different problems with `conditioner` that I ended up solving "outside" of it.

(1) wanting to mount 2 different modules on the same element
(2) wanting to manipulate many elements with some shared state

For (1) I use "composition": I create a module that will only run other modules on that element, like this:

```js
import moduleA from './module-a'
import moduleB from './module-b'

export default function (element) {
  // You know what you're doing
  let destroyA = moduleA(element)
  let destroyB = moduleB(element)

  return () => {
    destroyA()
    destroyB()
  }
}
```

For (2) I just run that logic outside of `conditioner` while bootstrapping the page or app:

```js
let boundModules = hydrate(document.body)
someOtherLogic()
```

**Comment by rikschennink** [comment]
@timseverien would this work for your situation:
```js
export default (modules) => {
    
    const api = {
        onsync: () => {},
        onunsync: () => {}
    };

    // tests if modules are in sync === all modules are mounted
    const testIfSynced = () => {
        if (modules.some(m => !m.mounted)) return;
        api.onsync(modules);
    };

    // listen for changes on modules
    modules.forEach(m => {
        // when a module mounts, we have to check the state of other modules
        m.onmount = testIfSynced;

        // when a single modules unmounts, we're always out of sync
        m.onunmount = () => api.onunsync(modules);
    });

    return api;
}
```
Usage

```js

// lets go!
const mySync = sync(conditioner.hydrate(document.documentElement));

mySync.onsync = (modules) => {
  console.log('now in sync', modules);
}

mySync.onunsync = (modules) => {
  console.log('no longer in sync', modules);
}
```

**Comment by timseverien** [comment]
I’m considering now using Conditioner now and initialise the components manually in views. This way I don’t have to look up children components after initialisation, which will make the code much simpler to comprehend.

Nonetheless, my use case shouldn’t be the criteria to accept or decline this PR. Do we think this is a cool feature to have, or do we want to stick with the concept that every module (or at least initialisation of those) should be completely isolated, thus handled with callbacks? Maybe the complexity of resolving the Promise for non-contextual modules only is too confusing to the user.

I’m totally fine with closing this for the above reasons.

**Comment by rikschennink** [comment]
@timseverien I’ll close it. Mainly because it’s breaking and while adding some convenience it also removes some flexibility and adds to the package weight (only a little bit), I purposely build Conditioner V2 to be flexible and small so it can be extended when needed so in that spirit this doesn’t fit and an additional custom helper function would be sufficient to work around it. (I’m typing this on beta of iOS13 so this might be a long sentence, I don’t dare scroll back :D)

**Pull request closed without merging**
